name: CI
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get Go version
        run: |
          echo "::set-output name=version::$(grep -E "^go [0-9]+\.[0-9]+" go.mod)"
        id: go-version
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ steps.go-version.outputs.version }}"
      - name: Cache
        uses: actions/cache@v2.1.7
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.go-version }}
      - name: Get dependencies
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: |
          go get -v -t -d ./...
      - name: Build
        run: |
          go build -v ./main.go

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest
